# Generated by Django 2.0.6 on 2019-05-31 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Student First Name', max_length=300)),
                ('other_name', models.CharField(help_text='Student Middle Name', max_length=300)),
                ('last_name', models.CharField(help_text='Student Last Name', max_length=300)),
                ('mugshot', models.ImageField(blank=True, null=True, upload_to='student/image/%Y/%m/%d')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Rather Not Mention')], default='male', help_text="Student's Gender", max_length=10)),
                ('student_class', models.CharField(choices=[('JSS1', 'jss1'), ('JSS2', 'jss2'), ('JSS3', 'jss3'), ('SS1', 'ss1'), ('SS2', 'ss2'), ('SS3', 'ss3')], default='JSS1', help_text="Student's Class", max_length=50)),
                ('date_of_birth', models.DateField(help_text='Format: YYYY-MM-DD')),
                ('date_admitted', models.DateField(help_text='Format: YYYY-MM-DD')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Student's Profile",
            },
        ),
    ]
