# Generated by Django 2.0.6 on 2019-01-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20181106_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mugshot',
            field=models.ImageField(blank=True, null=True, upload_to='student/image/%Y/%m/%d'),
        ),
    ]
