# Generated by Django 2.0.6 on 2019-01-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20190105_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(help_text='Student First Name', max_length=300),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Rather Not Mention')], default='male', help_text="Student's Gender", max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(help_text='Student Last Name', max_length=300),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='other_name',
            field=models.CharField(help_text='Student Middle Name', max_length=300),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.CharField(choices=[('JSS1', 'jss1'), ('JSS2', 'jss2'), ('JSS3', 'jss3'), ('SS1', 'ss1'), ('SS2', 'ss2'), ('SS3', 'ss3')], default='JSS1', help_text="Student's Class", max_length=50),
        ),
    ]
