# Generated by Django 2.0.6 on 2018-11-06 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20181106_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
