# Generated by Django 2.0.6 on 2019-01-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20181106_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='mugshot',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/images/%Y/%m/%d'),
        ),
    ]
