# Generated by Django 2.0.6 on 2019-01-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20190105_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.FileField(blank=True, default='text.txt', null=True, upload_to='teacher/file/%Y/%m/%d'),
        ),
    ]
