# Generated by Django 2.0.6 on 2019-01-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('can_enroll', 'Enroll In Course'),)},
        ),
    ]
