# Generated by Django 2.0.6 on 2018-10-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='timestamp',
        ),
    ]
