# Generated by Django 2.0.6 on 2019-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20181106_1008'),
        ('courses', '0004_remove_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to='students.StudentProfile'),
        ),
    ]
